apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nginx-deployment 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        run: serviceone 
    spec: 
      containers: 
      - name: nginx 
        image: nginx:1.16.1
        ports: 
        - containerPort: 80
      volumes:
      - name: nginx-vol
        hostPath:
          path: /etc/nginx/conf.d/