apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-web-app
  name: simple-web-app-gui-test
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: simple-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      containers:
      - args:
        - -Dconfig.file=/etc/simple-web-app/application.conf
        image: lmenezes/simple-web-app:0.9,4
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: simple-web-app
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/db/simple-web-app
          name: db
        - mountPath: /etc/simple-web-app
          name: config
        - mountPath: /opt/simple-web-app/logs/
          name: logs
        - mountPath: /tmp
          name: tmp
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 20000Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: db
      - configMap:
          defaultMode: 420
          name: simple-web-app-gui
        name: config
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: tmp
